---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: microservice1-svc
  name: microservice1-svc
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: microservice1-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: microservice1-svc
    spec:
      containers:
      - image: docker.io/depaniagua/microservice1
        imagePullPolicy: IfNotPresent
        name: microservice1-svc
         env:
        - name: API_QUEUE
          value: "192.168.50.4"
        ports:
        - containerPort: 3010
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: microservice1-svc
  name: microservice1-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3010
  selector:
    run: microservice1-svc
  sessionAffinity: None
  type: LoadBalancer